### ISSUE TITLE
Zone #1 - Environment 

### ISSUE THREAD

**Issue by JCKortlang** [Nkury/Math-Quest#1]
Fleshed out environment that loosely follows our specifications.
Environment should have textures. - @JCKortlang can help make these.
Three must haves: 
Bandit camp near boulder. 
Will require a script to update the Cabin / Troll Camp that has the dynamite.
Textures are not required for this.
Wandering enemies. - @Nkury or @JCKortlang can help with scripting.
Should contain some ambient objects (Trees, foliage, etc.) but this is low priority compared to everything else. 
If you feel overwhelmed delegate to @brandonshreve or @JCKortlang.

**Comment by brandonshreve** [comment]
😢
